import animal from '../assets/animal.jpg'
import animal2 from '../assets/animal2.jpg'
import animal3 from '../assets/animal3.jpg'
import animal4 from '../assets/animal4.jpg'
import art from '../assets/art.jpg'
import art2 from '../assets/art2.jpg'
import art3 from '../assets/art3.jpg'
import art4 from '../assets/art4.jpg'
import car from '../assets/car.jpg'
import car2 from '../assets/car2.jpg'
import car3 from '../assets/car3.jpg'
import car4 from '../assets/car4.jpg'
import car5 from '../assets/car5.jpg'
import cityscape from '../assets/cityscape.jpg'
import cityscape2 from '../assets/cityscape2.jpg'
import cityscape3 from '../assets/cityscape3.jpg'
import cityscape4 from '../assets/cityscape4.jpg'
import housing from '../assets/housing.jpg'
import housing2 from '../assets/housing2.jpg'
import housing3 from '../assets/housing3.jpg'
import housing4 from '../assets/housing4.jpg'
import nature from '../assets/nature.jpg'
import nature2 from '../assets/nature2.jpg'
import nature3 from '../assets/nature3.jpg'
import nature4 from '../assets/nature4.jpg'
import nature5 from '../assets/nature5.jpg'
import tech from '../assets/tech.jpg'
import tech2 from '../assets/tech2.jpg'
import tech3 from '../assets/tech3.jpg'
import tech4 from '../assets/tech4.jpg'
import travel from '../assets/travel.jpg'
import travel2 from '../assets/travel2.jpg'
import travel3 from '../assets/travel3.jpg'
import travel4 from '../assets/travel4.jpg'


export {animal, animal2, animal3, animal4, art, art2, art3, art4, car, car2, car3, car4, car5, cityscape, cityscape2, cityscape3, cityscape4, housing, housing2, housing3, housing4, nature, nature2, nature3, nature4, nature5, tech, tech2, tech3, tech4, travel, travel2, travel3, travel4}